[build]
  command = "pip install -r requirements.txt"
  functions = "functions"
  publish = "."

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app"
  status = 200

[dev]
  command = "python app.py"
  port = 5000
  autolaunch = false
